# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf05a7b31fca60f5aa6ed88fafca318f5527e551d16e38719d89764c52db3f69d58e6368fa3fbafd140cd18c4f7809ca67df37855dc962541c8dad99229c3cfe

test:
  secret_key_base: d4b3879d426983337e45ad1ce7ab00070bb7bb4a174fa1016170da415a21d8593b0aa4d3b4abe0e0747801d4eca2e8b52693a34f5cf39d18075a570abe5fe559

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
